### ISSUE TITLE
Fails uploading the docker image?

### ISSUE THREAD

**Issue by mochadwi** [softartdev/docker-android-fastlane#1]
https://github.com/softartdev/docker-android-fastlane/commit/a50228594bc5c059ba92a99c8157bf2eed2d95d3

we might needed your latest images to be build and published to hub.docker.com 🙏 

https://github.com/mochadwi/lakoo-android-ndk/commit/3b663b0851f5f0f7b17d36e1ce2f22cf1b0003c5

**Comment by softartdev** [comment]
Latest image (version 30) has been published: 
https://hub.docker.com/r/softartdev/android-fastlane/tags
What exactly is your issue?

**Comment by mochadwi** [comment]
Looks like there's an issue in our scripting CI we forgot to add `bundle install fastlane`, as we cannot runs the `bundle install fastlane` inside a Docker image

**Comment by softartdev** [comment]
fastlane installed from gems: [`gem install fastlane`](https://github.com/softartdev/docker-android-fastlane/blob/master/Dockerfile#L29)
