### ISSUE TITLE
Android 34 planned update

### ISSUE THREAD

**Issue by RowanG1** [softartdev/docker-android-fastlane#5]
Is there any date in mind for the Android 34 update?

**Comment by softartdev** [comment]
Thank you for your interest! We have updated the [image on Docker Hub](https://hub.docker.com/repository/docker/softartdev/android-fastlane), and you can now pull the [new version](https://hub.docker.com/layers/softartdev/android-fastlane/34/images/sha256-0755b8bdeee199dd6f60d2dcff91145a40e5c90c2e6e66bad1154f9407e1423f?context=repo). Please don't hesitate to reach out if you have any more questions :)
